<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="9" hostname="DESKTOP-6M54JAQ" failures="1" tests="1" name="Default test" time="24.672" errors="0" timestamp="2024-08-21T15:53:37 IST">
  <testcase classname="testcase.Login" name="login" time="6.948">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://demo.workorbits.com/dashboard/ongoing1] but found [https://demo.workorbits.com/]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://demo.workorbits.com/dashboard/ongoing1] but found [https://demo.workorbits.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testcase.Login.login(Login.java:32)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="testcase.Login" name="validation_On_NewPassword" time="0.0">
    <ignored/>
  </testcase> <!-- validation_On_NewPassword -->
  <testcase classname="testcase.Login" name="validation_for_empty_pass" time="0.0">
    <ignored/>
  </testcase> <!-- validation_for_empty_pass -->
  <testcase classname="testcase.Login" name="validation_On_Empty_NewPassword" time="0.0">
    <ignored/>
  </testcase> <!-- validation_On_Empty_NewPassword -->
  <testcase classname="testcase.Login" name="login_with_valid_email_and_pass" time="0.0">
    <ignored/>
  </testcase> <!-- login_with_valid_email_and_pass -->
  <testcase classname="testcase.Login" name="validation_for_invalid_PhEmail" time="0.0">
    <ignored/>
  </testcase> <!-- validation_for_invalid_PhEmail -->
  <testcase classname="testcase.Login" name="validation_On_Empty_OTP" time="0.0">
    <ignored/>
  </testcase> <!-- validation_On_Empty_OTP -->
  <testcase classname="testcase.Login" name="login_with_valid_phNum_pass" time="0.0">
    <ignored/>
  </testcase> <!-- login_with_valid_phNum_pass -->
  <testcase classname="testcase.Login" name="validation_For_empty_emailPhone" time="0.0">
    <ignored/>
  </testcase> <!-- validation_For_empty_emailPhone -->
  <testcase classname="testcase.Login" name="forgot_pass_with_valid_email" time="0.0">
    <ignored/>
  </testcase> <!-- forgot_pass_with_valid_email -->
</testsuite> <!-- Default test -->
